-
  name: Install python dependencies
  hosts: all
  tasks:
    - name: dependencies
      yum: name='{{ item }}' state=present
      with_items:
        - python
        - python-setuptools
        - python-devel
        - build-essential
        - python-pip
        - python-mysqldb
